apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlm-scheduler
spec:
  selector:
    matchLabels:
      app: wlm-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: wlm-scheduler
    spec:
      containers:
      - name: wlm-scheduler
        image: trilio/tvr-workloadmgr-api:1.7
        command: [ "/home/rhv/myansible/bin/workloadmgr-scheduler" ]
        args: [ "--config-file=/etc/workloadmgr/conf/workloadmgr.conf" ]
        ports:
        - containerPort: 8780
          name: wlm-scheduler
        - containerPort: 8888
          name: websocket
        securityContext:
          privileged: true
        volumeMounts:
        - name: tvault-config
          mountPath: /etc/tvault-config
          readOnly: false
        - name: workloadmgr-config
          mountPath: /etc/workloadmgr/conf/workloadmgr.conf
          subPath: workloadmgr.conf
        - name: vault-config
          mountPath: /etc/workloadmgr/vault.conf
          subPath: vault.conf
      volumes:
        - name: tvault-config
          configMap:
            name: tvault-config-file
        - name: workloadmgr-config
          configMap:
            name: workloadmgr-config-file
        - name: vault-config
          configMap:
            name: vault-config-file
      imagePullSecrets:
        - name: regcred-trilio
---
apiVersion: v1
kind: Service
metadata:
  name: wlm-scheduler
spec:
  ports:
  - name: http
    port: 8780
  - name: websocket
    port: 8888
  selector:
    app: wlm-scheduler
  type: ClusterIP

