---
# handlers file for kubernetes
- name: Restart Docker
  service: 
    name: docker
    enabled: yes 
    state: restarted

- name: Restart Kubelet
  service: 
    name: kubelet
    enabled: yes 
    state: restarted
