

namespace: trilio


metallb:
   enabled: true
   configInline:
     address-pools:
     - name: default
       protocol: layer2
       addresses:
       - 142.44.219.121/32


# mariadb:
#   rootUser.password: trilio
#   galera.bootstrap.forceSafeToBootstrap: true
#   galera.bootstrap.bootstrapFromNode: 0
#   podManagementPolicy: Parallel
