---
# handlers file for haproxy
- name: restart haproxy
  service: 
    name: haproxy
    enabled: yes 
    state: restarted
  
- name: restart keepalived
  service: 
    name: keepalived
    enabled: yes 
    state: restarted